config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from user.views import *

urlpatterns = [
    path('staff/', admin.site.urls),    
    path('accounts/', include('user.urls')),
    path('exams/', include('exam.urls')),
    path('groups/', include('group.urls')),
    path('', home, name='home'),
    path('', include('urls.urls'))
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', exam_list, name='exam_list'),
    path('add/', add_exam, name='add_exam'),
    path('<int:exam_id>/', exam_detail, name='exam_detail'),
    path('<int:exam_id>/take/', take_exam, name='take_exam'),
    path('<int:exam_id>/delete/', delete_exam, name='delete_exam'),
    path('<int:exam_id>/results/', show_result, name='show_result'),
    path('<int:exam_id>/add_question/', add_question, name='add_question'),
    path('questions/<int:question_id>/', question_detail, name='question_detail'),
    path('questions/<int:question_id>/edit/', edit_question, name='edit_question'),
    path('questions/<int:question_id>/delete/', delete_question, name='delete_question'),
]

exam/models.py
from django.db import models
from user.models import CustomUser
from django.utils import timezone

class Course(models.Model):
    course_name = models.CharField(max_length=100)

    def __str__(self):
        return self.course_name
    
class Exam(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    exam_name = models.CharField(max_length=50)
    total_marks = models.PositiveIntegerField()
    total_question_number = models.PositiveIntegerField()
    duration_minutes = models.PositiveIntegerField(default=60)  # Duration of the exam in minutes

    def __str__(self):
        return self.exam_name

    @property
    def end_time(self):
        return timezone.now() + timezone.timedelta(minutes=self.duration_minutes)

class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=400)
    content = models.TextField(blank=True, null=True)
    mark = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.question_text

class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option_text = models.CharField(max_length=300, blank=True, null=True)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.option_text


class Result(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(default=0)
    date_taken = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student.username}'s result for {self.exam.exam_name}"
    
class Answer(models.Model):
    result = models.ForeignKey(Result, on_delete=models.CASCADE)
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_option = models.ForeignKey(Option, on_delete=models.CASCADE, null=True, blank=True)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"Answer for {self.question.question_text} by {self.student.username}"

exam/forms.py
from django import forms
from .models import *
from django.forms import inlineformset_factory


class OptionForm(forms.Form):
    def __init__(self, *args, **kwargs):
        questions = kwargs.pop('questions')
        super(OptionForm, self).__init__(*args, **kwargs)
        for question in questions:
            options = Option.objects.filter(question=question)
            self.fields[f'question_{question.id}'] = forms.ChoiceField(
                choices=[(option.id, option.option_text) for option in options],
                widget=forms.RadioSelect,
                label=question.question_text
            )

class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['course', 'exam_name', 'total_marks', 'total_question_number']
        widgets = {
            'course': forms.Select(attrs={'class': 'form-control'}),
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'content', 'mark']

OptionFormSet = forms.inlineformset_factory(
    Question, Option, fields=('option_text', 'is_correct'), extra=4, can_delete=False
)

exam/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.http import HttpResponseNotFound
from django.contrib import messages
from django.utils import timezone
from django.db.models import Count
from .models import *
from .forms import *

@login_required
def exam_list(request):
    exams = Exam.objects.all()
    exam_count = exams.count()
    courses = Course.objects.all()
    courses_count = courses.count()

    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'teacher/exams/exam_list.html', {'exams': exams, 'exam_count': exam_count})
        elif request.user.is_student:
            return render(request, 'student/exams/exam_list.html', {'exams': exams, 'exam_count': exam_count})
        elif request.user.is_staff:
            return render(request, 'staff/exams/course_list.html', {'courses': courses, 'courses_count': courses_count})

@login_required
def take_exam(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    questions = exam.question_set.all()
    
    if request.method == 'POST':
        form = OptionForm(request.POST, questions=questions)
        if form.is_valid():
            total_mark = 0
            for question in questions:
                selected_option_id = form.cleaned_data.get(f'question_{question.id}')
                if selected_option_id:
                    selected_option = get_object_or_404(Option, pk=selected_option_id)
                    total_mark += question.mark if selected_option.is_correct else 0
            
            # Create a result object for the student's performance in the exam
            result = Result.objects.create(student=request.user, exam=exam, score=total_mark)
            
            # Save the selected options and answers
            for question in questions:
                selected_option_id = form.cleaned_data.get(f'question_{question.id}')
                if selected_option_id:
                    selected_option = get_object_or_404(Option, pk=selected_option_id)
                    is_correct = selected_option.is_correct
                else:
                    is_correct = False
                
                Answer.objects.create(result=result, student=request.user, question=question,
                                       selected_option=selected_option, is_correct=is_correct)
            
            messages.success(request, 'Exam submitted successfully!')
            return redirect('show_result', exam_id=exam_id)
    else:
        form = OptionForm(questions=questions)
        
    return render(request, 'student/exams/take_exam.html', {'exam': exam, 'questions': questions, 'form': form})

def show_result(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    
    # Get the most recent result for the current student and exam
    result = Result.objects.filter(student=request.user, exam=exam).latest('date_taken')

    student_answers = Answer.objects.filter(result=result)
    return render(request, 'student/exams/show_result.html', {'exam': exam, 'result': result, 'student_answers': student_answers})

def save_student_answers(exam, questions, request):
    # Get the currently logged-in student
    student = request.user

    # Loop through each question and save the student's selected options
    for question in questions:
        selected_option_id = request.POST.get(f'question_{question.id}')
        if selected_option_id:
            selected_option = get_object_or_404(Option, pk=selected_option_id)
            is_correct = selected_option.is_correct
        else:
            selected_option = None
            is_correct = False
        
        # Create an Answer object for each question
        Answer.objects.create(student=student, exam=exam, question=question, selected_option=selected_option, is_correct=is_correct)

@login_required
def show_result(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    result = Result.objects.filter(student=request.user, exam=exam).latest('date_taken')
    
    student_answers = Answer.objects.filter(result=result)
    return render(request, 'student/exams/show_result.html', {'exam': exam, 'result': result, 'student_answers': student_answers})

@login_required
def add_exam(request):
    if request.user.is_authenticated and request.user.is_teacher:
        if request.method == 'POST':
            form = ExamForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('exam_list')
        else:
            form = ExamForm()
        
        return render(request, 'teacher/exams/add_exam.html', {'form': form})
    elif request.user.is_authenticated and request.user.is_student:
        return HttpResponseNotFound('<h1>Page not found</h1>')
    
    else:
        return render(request, 'staff/exams/add_exam.html', {'form': form})

@login_required
def exam_detail(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    questions = exam.question_set.all() 

    questions_count = questions.count()
    return render(request, 'teacher/exams/exam_detail.html', {'exam': exam , 'questions': questions, 'questions_count': questions_count})

@login_required
def add_question(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        option_formset = OptionFormSet(request.POST)
        if question_form.is_valid() and option_formset.is_valid():
            question = question_form.save(commit=False)
            question.exam = exam
            question.save()
            option_formset.instance = question
            option_formset.save()
            return redirect('exam_detail', exam_id=exam_id)  # Redirect back to the exam detail page
    else:
        question_form = QuestionForm()
        option_formset = OptionFormSet()

    return render(request, 'teacher/exams/add_question.html', {'exam': exam, 'question_form': question_form, 'option_formset': option_formset})

@login_required
def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    exam = get_object_or_404(Exam, pk=question.exam.id)

    return render(request, 'teacher/exams/question_detail.html', {'question': question, 'exam': exam})

@login_required
def edit_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    OptionFormSet = modelformset_factory(Option, fields=('option_text', 'is_correct'), extra=1)
    
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = OptionFormSet(request.POST, queryset=Option.objects.filter(question=question))
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('question_detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
        formset = OptionFormSet(queryset=Option.objects.filter(question=question))
    
    return render(request, 'teacher/exams/edit_question.html', {'form': form, 'formset': formset, 'question': question})

@login_required
def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('exam_detail', exam_id=question.exam.id)

@login_required
def delete_exam(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    
    exam.delete()
    return redirect('exam_list')

@login_required
def student_results(request):
    # Retrieve all results for the current student
    student_results = Result.objects.filter(student=request.user).order_by('-date_taken')
    
    return render(request, 'student/exams/results.html', {'result': student_results})

@login_required
def result_detail(request, result_id):
    result = get_object_or_404(Result, student=request.user, pk=result_id)
    student_answers = Answer.objects.filter(result=result)
    return render(request, 'student/exams/result_detail.html', {'result': result, 'student_answers': student_answers})

@login_required
def show_courses(request):
    courses = Course.objects.annotate(
        exam_count=Count('exam', distinct=True),
        question_count=Count('exam__question', distinct=True)
    )

    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'teacher/courses/course_list.html', {'courses': courses})
        elif request.user.is_student:
            return render(request, 'student/courses/course_list.html', {'courses': courses})
        elif request.user.is_staff:
            return render(request, 'staff/courses/course_list.html', {'courses': courses})

@login_required
def course_detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    exams = Exam.objects.filter(course=course)
    questions = Question.objects.filter(exam__course=course)

    return render(request, 'student/courses/course_detail.html', {'course': course, 'exams': exams, 'questions': questions})

@login_required
def all_results(request):
    try:
        results = Result.objects.all()
        if not results:
            # Handle the case when there are no results
            return render(request, 'teacher/results/no_results.html')
        else:
            return render(request, 'teacher/results/results.html', {'results': results})
    except Result.DoesNotExist:
        # Handle the case when no Result objects exist
        return render(request, 'teacher/results/no_results.html')
    
@login_required
def result_detail(request, result_id):
    result = get_object_or_404(Result, pk=result_id)
    
    student_answers = Answer.objects.filter(result=result)
    

templates/teacher/exams/add_exam.html
{% extends 'teacher/base.html' %} 
{% block content %}
<header class="bg-gray-800 text-white py-4 px-6">
  <div class="max-w-3xl mx-auto flex justify-between items-center">
    <h1 class="text-2xl font-semibold">Exams Add</h1>
    <a href="{% url 'exam_list' %}" class="text-gray-300 hover:text-gray-100">
      Back to Exams
    </a>
  </div>
</header>

<main class="p-6">
  <div class="max-w-md mx-auto bg-white shadow-md rounded-lg overflow-hidden">
    <form class="p-6" method="post">
      {% csrf_token %}
      <div class="mb-4">
        <label for="course" class="block text-gray-700 text-sm font-bold mb-2">
          Course:
        </label>
        {{ form.course }}
      </div>
      <div class="mb-4">
        <label for="exam_name" class="block text-gray-700 text-sm font-bold mb-2">
          Exam Name:
        </label>
        <input
          type="text"
          id="exam_name"
          name="exam_name"
          class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          required
        />
      </div>
      <div class="mb-4">
        <label for="total_marks" class="block text-gray-700 text-sm font-bold mb-2">
          Total Marks:
        </label>
        <input
          type="number"
          id="total_marks"
          name="total_marks"
          class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          required
        />
      </div>
      <div class="mb-4">
        <label for="total_question_number" class="block text-gray-700 text-sm font-bold mb-2">
          Total Questions:
        </label>
        <input
          type="number"
          id="total_question_number"
          name="total_question_number"
          class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          required
        />
      </div>
      <button
        type="submit"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
      >
        Add Exam
      </button>
    </form>
  </div>
</main>

{% endblock content %}

templates/teacher/exams/add_question.html
{% extends 'teacher/base.html' %} {% load crispy_forms_tags %} {% block content %}
<header class="bg-gray-800 text-white py-4 px-6">
  <div class="max-w-3xl mx-auto flex justify-between items-center">
    <h1 class="text-2xl font-semibold">Exams Detail :: {{exam.exam_name}}</h1>
    <a
      href="{% url 'exam_detail' exam.pk %}"
      class="text-gray-300 hover:text-gray-100"
    >
      Back to Exam
    </a>
  </div>
</header>

<main class="my-12">
  <div class="max-w-3xl mx-auto bg-white shadow-md rounded-lg overflow-hidden">
    <form class="p-6" method="post">
      {% csrf_token %} {{ question_form | crispy }} {{option_formset.management_form}} {% for form in option_formset.forms %} {{ form | crispy }} {% endfor %}
      <button
        type="submit"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
      >
        Add Exam
      </button>
    </form>
  </div>
</main>

{% endblock content %}

templates/teacher/exams/edit_question.html
{% extends 'teacher/base.html' %} {% load crispy_forms_tags %} {% block content %}
<header class="bg-gray-800 text-white py-4 px-6">
    <div class="max-w-3xl mx-auto flex justify-between items-center">
      <h1 class="text-2xl font-semibold">{{ question.question_text }}</h1>
      <a
        href="{% url 'question_detail' question.pk %}"
        class="text-gray-300 hover:text-gray-100"
      >
        Back to Question
      </a>
    </div>
  </header>
  
<main class="my-12">
  <div class="max-w-3xl mx-auto bg-white shadow-md rounded-lg overflow-hidden">
    <form class="p-6" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        {{ formset.management_form }}
        {% for subform in formset %}
        <div class="option-form">
          {{ subform | crispy }}
        </div>
        {% endfor %}
        <button
          type="submit"
          class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
        >
          Save Changes
        </button>
    </form>
  </div>
</main>
{% endblock %}

templates/teacher/exams/exam_detail.html
{% extends 'teacher/base.html' %} {% block content %}
<header class="bg-gray-800 text-white py-4 px-6">
  <div class="max-w-3xl mx-auto flex justify-between items-center">
    <h1 class="text-2xl font-semibold">Exams Detail :: {{exam.exam_name}}</h1>
    <a href="{% url 'exam_list' %}" class="text-gray-300 hover:text-gray-100">
      Back to Exams
    </a>
  </div>
</header>

<main class="p-6">
  <div class="container mx-auto max-w-4xl">
    <div class="mb-6">
      <h2 class="text-lg font-semibold mb-2">Exam Information</h2>
      <div class="bg-white overflow-hidden">
        <div class="px-4 py-3 border-b border-gray-200">
          <span class="text-gray-600 font-semibold">Course:</span>
          <span class="text-gray-900">{{ exam.course }}</span>
        </div>
        <div class="px-4 py-3 border-b border-gray-200">
          <span class="text-gray-600 font-semibold">Total Marks:</span>
          <span class="text-gray-900">{{ exam.total_marks }}</span>
        </div>
        <div class="px-4 py-3">
          <span class="text-gray-600 font-semibold">Total Questions:</span>
          <span class="text-gray-900">{{ questions_count }}</span>
        </div>
      </div>
    </div>

    <table class="min-w-full">
      <thead>
        <tr>
          <th
            class="px-6 py-3 w-20 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
          >
            #
          </th>
          <th
            class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
          >
            Question
          </th>
          <th
            class="px-6 py-3 w-36 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider relative"
          >
            Mark
            <a
              href="{% url 'add_question' exam.pk %}"
              class="absolute right-3 text-2xl top-1.5 hover:text-green-600 cursor-pointer transition"
            >
              <i class="bi bi-plus-circle-dotted"></i>
            </a>
          </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for data in questions %}
        <tr class="hover:bg-green-50 cursor-pointer transition">
          <td class="px-6 py-4 whitespace-nowrap">
            <a href="{% url 'question_detail' data.pk %}">
              {{ forloop.counter }}
            </a>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <a href="{% url 'question_detail' data.pk %}">
              {{ data.question_text }}
            </a>
          </td>
          <td class="px-6 py-4 whitespace-nowrap flex items-center relative">
            <a href="{% url 'question_detail' data.pk %}"> {{ data.mark }} </a>

            <form class="absolute text-red-600 right-3 text-xl" action="{% url 'delete_question' data.pk %}" method="post">
              {% csrf_token %}
              <button type="submit">
                <i class="bi bi-trash3-fill"></i>
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock content %}

templates/teacher/exams/exam_list.html
{% extends 'teacher/base.html' %}

templates/teacher/exams/question_detail.html
{% extends 'teacher/base.html' %} {% block content %}

<header class="bg-gray-800 text-white py-4 px-6">
  <div class="max-w-6xl mx-auto flex justify-between items-center">
    <h1 class="text-3xl font-semibold text-white">
      {{ question.question_text }}
    </h1>
    <a href="{% url 'exam_detail' exam.id %}" class="text-gray-300 hover:text-gray-100">
      <i class="bi bi-arrow-left"></i> Back to Exam
    </a>
  </div>
</header>

<main class="mx-auto w-full">
  <div class="mt-8 max-w-5xl mx-auto">
    <div class="question-detail bg-white shadow-md rounded-lg p-6">
      <h2 class="text-xl font-semibold mb-4">
        {{ question.question_text }}

        <a href="{% url 'edit_question' question.id %}">
          <i class="bi bi-vector-pen"></i>
        </a>
      </h2>
      {% if question.content %}
      <p class="text-gray-700">{{ question.content }}</p>
      {% endif %}
      <p class="text-gray-700">Mark: {{ question.mark }}</p>
      <h3 class="text-lg font-semibold mt-6 mb-2">Options:</h3>
      <ol type="A" style="list-style-type: upper-latin">
        {% for option in question.option_set.all %}
        <li class="text-gray-700">
          {{ option.option_text }} {% if option.is_correct %}<span
            class="text-green-500"
            >(Correct)</span
          >{% endif %}
        </li>
        {% endfor %}
      </ol>
    </div>
  </div>
</main>

{% endblock content %}